### PR TITLE
[WIP] Create a Jenkins image that has sbt and terraform installed

### PR DESCRIPTION
**Pull request by alexwlchan**
This is part 1 of 2 to getting working Jenkins set up – part 2 will involve pushing the image to a Docker repository, and tweaking the Terraform config to use this image instead.

### CODE REVIEW

**Comment by kenoir** [comment]
Do we want to install some plugins here too? See: https://github.com/fabric8io/jenkins-docker/blob/master/Dockerfile#L3 

I think some plugins might install things outside the Jenkins home dir in which case they'd break on restart.

**Comment by alexwlchan** [comment]
Yep, let’s get plugins checked in as well. The more config in version control, the better. 👍

**Comment by kenoir** [comment]
Beep boop. Been open for 6 days!

**Comment by kenoir** [comment]
^ i bet there's a bit that will notify us of stale PRs :)

**Comment by kenoir** [comment]
Worth watching https://github.com/hashicorp/terraform/issues/8746 so that we can get Terraform to behave sensibly around IAM roles. Might even be worth contributing a PR if anyone has the will to write some golang.

**Comment by alexwlchan** [comment]
> ^ i bet there's a bot that will notify us of stale PRs :)

Yes, it’s called “daily standup”. 😉

**Comment by kenoir** [comment]
@alexwlchan even better than a robot!

**Comment by alexwlchan** [comment]
Most of the motivation for this change was to make the builds go faster. Things are significantly better than they used to be, so for now I’m putting this on ice.

**Comment by kenoir** [comment]
There is also flexibility and build pipelines. I would prefer to merge what is there now to ensure it doesn't go stale.

**Pull request closed without merging**
